# Dependencies
highlighter:      rouge
markdown:         kramdown

# Permalinks
permalink:        pretty

# Incude
include: [".well-known"]

# Gems
gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag

# Setup
title:            'Jasdev Singh'
description:      'Hi, I''m <a href="/about">Jasdev</a> <span>👋</span> I''m an engineer <span>📲</span>'
url:              http://jasdev.me
baseurl:          /

author:
  name:           'Jasdev Singh'
  url:            https://twitter.com/jasdev
  email:          jasdevs@gmail.com
  twitter:        jasdev

twitter:
  username:       jasdev
  url:            https://twitter.com/jasdev

paginate:         3

# Links
github:           https://github.com/jasdev
gyroscope:        https://gyrosco.pe/jasdev
instagram:        https://instagram.com/jasdev
soundcloud:       https://soundcloud.com/jasdev-singh
coach:            https://www.coach.me/users/3140daf3d432d7f0065b
