# Dependencies
highlighter:      rouge
markdown:         kramdown

# Permalinks
permalink:        pretty

# Incude
include: [".well-known"]

# Gems
gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-paginate

# Setup
title:            '@jasdev'
description:      'Hi, I''m <a href="https://twitter.com/jasdev" target="_blank">Jasdev</a> <span>👋</span> I''m an engineer <span>📲</span>'
url:              http://jasdev.github.io
baseurl:          /

author:
  name:           'Jasdev Singh'
  url:            https://twitter.com/jasdev
  email:          jasdevs@gmail.com

paginate:         3

# Links
github:           https://github.com/jasdev
twitter:          https://twitter.com/jasdev
gyroscope:        https://gyrosco.pe/jasdev
instagram:        https://instagram.com/jasdev
soundcloud:       https://soundcloud.com/jasdev-singh
coach:            https://www.coach.me/users/3140daf3d432d7f0065b
