# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Incude
include: [".well-known"]

# Gems
gems:
  - jemoji
  - jekyll-redirect-from

# Setup
title:            '@jasdev'
description:      'Hi, I''m <a href="https://twitter.com/jasdev" target="_blank">Jasdev</a> <span>👋</span> I work at <a href="http://imgur.com" target="_blank">Imgur</a> as an iOS and API Engineer <span>📲</span>'
url:              http://jasdev.github.io
baseurl:          /

author:
  name:           'Jasdev Singh'
  url:            https://twitter.com/jasdev

paginate:         5

# Custom vars

# User accounts
keybase:          https://keybase.io/jasdev
github:           https://github.com/jasdev
twitter:          https://twitter.com/jasdev
gyroscope:        https://gyrosco.pe/jasdev
instagram:        https://instagram.com/jasdev
soundcloud:       https://soundcloud.com/jasdev-singh
coach:            https://www.coach.me/users/3140daf3d432d7f0065b
