# Dependencies
highlighter:      rouge
markdown:         kramdown

# Permalinks
permalink:        pretty

# Incude
include: [".well-known"]

# Gems
gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag

# Setup
title:            'Jasdev Singh'
description:      'Hi, I''m <a href="/about">Jasdev</a>! I''m an engineer who loves reading, writing, and human performance.'
url:              http://jasdev.me
baseurl:          /

author:
  name:           'Jasdev Singh'
  url:            https://twitter.com/jasdev
  email:          jasdevs@gmail.com
  twitter:        jasdev

twitter:
  username:       jasdev
  url:            https://twitter.com/jasdev

paginate:         5

# Links
github:           https://github.com/jasdev
gyroscope:        https://gyrosco.pe/jasdev/helix/
instagram:        https://instagram.com/jasdev
soundcloud:       https://soundcloud.com/jasdev-singh
instapaper:       http://instapaper.com/p/jasdev
instapaper_rss:   http://instapaper.com/starred/rss/4750197/tes3ESKY5E01Sx4DKAfUYK9rUQ
